repos:
-   repo: local
    hooks:
    - id: black
      name: black
      language: system
      entry: black
      types: [python]
    - id: mypy
      name: mypy
      language: system
      entry: mypy
      types: [python]
      exclude: 'test/|setup.py'
